package com.example.domain.srs

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import kotlin.math.abs

/**
 * Conformance against the MAINTAINED REFERENCE, not against my own reading of it.
 *
 * `Fsrs6SpecComplianceTest` re-implements the published equations and checks `Fsrs6.kt` agrees. That
 * is worth having, but it shares an author with the code under test: any equation I misread, I
 * misread twice, and the test passes while the scheduler is wrong. Exactly that happened — three
 * deviations survived a green spec-compliance suite.
 *
 * The goldens are generated by CALLING py-fsrs's own methods (`_next_difficulty`, `_next_forget_stability`,
 * `_next_recall_stability`, `_short_term_stability`; `tools/generate_fsrs6_goldens.py`), so a disagreement here means
 * Yadora disagrees with the reference implementation, full stop. Two releases are checked:
 * - `golden_fsrs6_632.json`, py-fsrs 6.3.2: the live equations since POLICY YADORA-9 (a same-day Hard cannot shrink
 *   stability);
 * - `golden_fsrs6.json`, py-fsrs 6.3.1: the equations every review stamped YADORA-8 or earlier was computed with, and
 *   still replays with (`floorSameDayHard = false`).
 * Regenerate only to adopt a new reference version, and treat any new diff as a deliberate decision to record, never as
 * a test to relax.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [36])
class Fsrs6GoldenVectorTest {

    /** One reference release: its goldens, and whether Yadora's same-day Hard floor is on to reproduce it. */
    private class Reference(val file: String, val version: String, val floorSameDayHard: Boolean) {
        val golden: JSONObject by lazy {
            val text = javaClass.classLoader!!.getResourceAsStream(file)!!.bufferedReader().use { it.readText() }
            JSONObject(text).also { require(it.getString("pyFsrsVersion") == version) { "$file is not py-fsrs $version" } }
        }
    }

    private val references = listOf(
        Reference("golden_fsrs6_632.json", "6.3.2", floorSameDayHard = true),
        Reference("golden_fsrs6.json", "6.3.1", floorSameDayHard = false),
    )

    private val p = Fsrs6Parameters()

    /** The weights themselves must match, or every comparison below is meaningless. */
    @Test
    fun `the pinned parameter vector is the reference vector`() = references.forEach { ref ->
        val golden = ref.golden
        val arr = golden.getJSONArray("parameters")
        assertEquals("parameter count", arr.length(), p.weights.size)
        for (i in 0 until arr.length()) {
            assertEquals("w[$i]", arr.getDouble(i), p.weights[i], 0.0)
        }
        assertEquals("decay", golden.getDouble("decay"), -p.weights[20], 1e-12)
    }

    @Test
    fun `the forgetting curve matches the reference`() = references.forEach { ref ->
        val rows = ref.golden.getJSONArray("retrievability")
        for (i in 0 until rows.length()) {
            val row = rows.getJSONObject(i)
            val s = row.getDouble("s")
            val t = row.getDouble("t")
            assertEquals(
                "R(t=$t, S=$s)",
                row.getDouble("r"), Fsrs6.retrievability(t, s, p), 1e-12,
            )
        }
    }

    @Test
    fun `retention to interval inversion matches the reference`() = references.forEach { ref ->
        val rows = ref.golden.getJSONArray("intervals")
        for (i in 0 until rows.length()) {
            val row = rows.getJSONObject(i)
            val s = row.getDouble("s")
            val req = row.getDouble("req")
            val expected = row.getDouble("days")
            val actual = Fsrs6.intervalDays(s, req, p)
            assertTrue(
                "interval(S=$s, R=$req): expected $expected got $actual",
                abs(expected - actual) <= 1e-9 * maxOf(1.0, abs(expected)),
            )
        }
    }

    /**
     * Every state transition the reference can perform. Split by kind so a failure names which
     * equation drifted rather than just "something is off".
     */
    @Test
    fun `every state transition matches the reference`() = references.forEach { ref ->
        val rows = ref.golden.getJSONArray("transitions")
        var difficulty = 0
        var shortTerm = 0
        var longTerm = 0

        for (i in 0 until rows.length()) {
            val row = rows.getJSONObject(i)
            val grade = gradeOf(row.getInt("g"))
            when (row.getString("kind")) {
                "difficulty" -> {
                    val d = row.getDouble("d")
                    assertClose(
                        "nextDifficulty(D=$d, $grade)",
                        row.getDouble("out"), Fsrs6.nextDifficulty(d, grade, p),
                    )
                    difficulty++
                }
                "shortTerm" -> {
                    val s = row.getDouble("s")
                    assertClose(
                        "py-fsrs ${ref.version} shortTermStability(S=$s, $grade)",
                        row.getDouble("out"), Fsrs6.shortTermStability(s, grade, p, ref.floorSameDayHard),
                    )
                    shortTerm++
                }
                "longTerm" -> {
                    val s = row.getDouble("s")
                    val d = row.getDouble("d")
                    val r = row.getDouble("r")
                    val actual = if (grade == Grade.Again) {
                        Fsrs6.postLapseStability(MemoryState(s, d), r, p)
                    } else {
                        Fsrs6.recallStability(MemoryState(s, d), r, grade, p)
                    }
                    assertClose("stability(S=$s, D=$d, R=$r, $grade)", row.getDouble("out"), actual)
                    longTerm++
                }
            }
        }

        // Guard against a silently empty or truncated resource passing as "all matched".
        assertTrue("difficulty vectors present", difficulty >= 100)
        assertTrue("short-term vectors present", shortTerm >= 100)
        assertTrue("long-term vectors present", longTerm >= 1000)
    }

    /**
     * The COMPOSED step, not just the pieces.
     *
     * Testing the internals alone leaves the seams unchecked: which branch a given elapsed time
     * selects, whether stability is computed from the OLD difficulty before difficulty is updated,
     * and what final clamps are applied. A max-stability clamp of 3650 days that the reference does
     * not have lived here undetected while every internal-function vector matched.
     */
    @Test
    fun `the composed transition matches the reference`() = references.forEach { ref ->
        val rows = ref.golden.getJSONArray("fullState")
        for (i in 0 until rows.length()) {
            val row = rows.getJSONObject(i)
            val s = row.getDouble("s")
            val d = row.getDouble("d")
            val t = row.getDouble("t")
            val grade = gradeOf(row.getInt("g"))
            val actual = Fsrs6.nextState(MemoryState(s, d), t, grade, p, ref.floorSameDayHard)
            assertClose("py-fsrs ${ref.version} nextState(S=$s, D=$d, t=$t, $grade).stability", row.getDouble("outS"), actual.stability)
            assertClose("py-fsrs ${ref.version} nextState(S=$s, D=$d, t=$t, $grade).difficulty", row.getDouble("outD"), actual.difficulty)
        }
        assertTrue("full-state vectors present", rows.length() >= 1000)
    }

    /** Initial seeding: the reference clamps initial stability to the MINIMUM only. */
    @Test
    fun `initial states match the reference`() = references.forEach { ref ->
        val rows = ref.golden.getJSONArray("initialStates")
        assertEquals("one per grade", 4, rows.length())
        for (i in 0 until rows.length()) {
            val row = rows.getJSONObject(i)
            val grade = gradeOf(row.getInt("g"))
            val actual = Fsrs6.initialState(grade, p)
            assertClose("initialState($grade).stability", row.getDouble("s"), actual.stability)
            assertClose("initialState($grade).difficulty", row.getDouble("d"), actual.difficulty)
        }
    }

    /**
     * The two releases differ in exactly one thing: a same-day Hard. Every other vector is identical, and where they
     * differ 6.3.2 keeps stability at least where it was (S = 100 keeps 100; 6.3.1 drops it to about 45).
     */
    @Test
    fun `py-fsrs 6_3_2 differs from 6_3_1 only in a same-day Hard, which no longer shrinks stability`() {
        val (new, old) = references
        var differing = 0
        for (section in listOf("transitions", "fullState")) {
            val a = new.golden.getJSONArray(section)
            val b = old.golden.getJSONArray(section)
            assertEquals(a.length(), b.length())
            for (i in 0 until a.length()) {
                val x = a.getJSONObject(i)
                val y = b.getJSONObject(i)
                if (x.toString() == y.toString()) continue
                differing++
                val sameDay = if (section == "transitions") x.getString("kind") == "shortTerm" else x.getDouble("t") < 1.0
                assertTrue("only a same-day Hard differs: $x against $y", x.getInt("g") == 2 && sameDay)
                val outS = if (section == "transitions") "out" else "outS"
                assertTrue("6.3.2 keeps stability: $x", x.getDouble(outS) >= x.getDouble("s") - 1e-12)
                assertTrue("6.3.1 shrank it: $y", y.getDouble(outS) < y.getDouble("s"))
            }
        }
        assertEquals("66 single-equation and 66 composed vectors", 132, differing)
        val mature = MemoryState(100.0, 5.0)
        assertEquals(100.0, Fsrs6.nextState(mature, 0.0, Grade.Hard, p, floorSameDayHard = true).stability, 1e-9)
        assertTrue(Fsrs6.nextState(mature, 0.0, Grade.Hard, p, floorSameDayHard = false).stability < 46.0)
    }

    private fun assertClose(what: String, expected: Double, actual: Double) {
        val tol = 1e-9 * maxOf(1.0, abs(expected))
        assertTrue("$what: expected $expected got $actual", abs(expected - actual) <= tol)
    }

    private fun gradeOf(v: Int) = when (v) {
        1 -> Grade.Again
        2 -> Grade.Hard
        3 -> Grade.Good
        else -> Grade.Easy
    }
}
