package com.example.domain.srs

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import kotlin.math.abs

/**
 * Conformance against the MAINTAINED REFERENCE, not against my own reading of it.
 *
 * `Fsrs6SpecComplianceTest` re-implements the published equations and checks `Fsrs6.kt` agrees. That
 * is worth having, but it shares an author with the code under test: any equation I misread, I
 * misread twice, and the test passes while the scheduler is wrong. Exactly that happened — three
 * deviations survived a green spec-compliance suite.
 *
 * `golden_fsrs6.json` is generated by CALLING py-fsrs 6.3.1's own methods (`_next_difficulty`,
 * `_next_forget_stability`, `_next_recall_stability`, `_short_term_stability`), so a disagreement
 * here means Yadora disagrees with the reference implementation, full stop. Regenerate with
 * scratchpad `golden.py` when the pinned reference version changes — and treat any new diff as a
 * deliberate decision to record, never as a test to relax.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [36])
class Fsrs6GoldenVectorTest {

    private val golden: JSONObject by lazy {
        val text = javaClass.classLoader!!.getResourceAsStream("golden_fsrs6.json")!!
            .bufferedReader().use { it.readText() }
        JSONObject(text)
    }

    private val p = Fsrs6Parameters()

    /** The weights themselves must match, or every comparison below is meaningless. */
    @Test
    fun `the pinned parameter vector is the reference vector`() {
        val arr = golden.getJSONArray("parameters")
        assertEquals("parameter count", arr.length(), p.weights.size)
        for (i in 0 until arr.length()) {
            assertEquals("w[$i]", arr.getDouble(i), p.weights[i], 0.0)
        }
        assertEquals("decay", golden.getDouble("decay"), -p.weights[20], 1e-12)
    }

    @Test
    fun `the forgetting curve matches the reference`() {
        val rows = golden.getJSONArray("retrievability")
        for (i in 0 until rows.length()) {
            val row = rows.getJSONObject(i)
            val s = row.getDouble("s")
            val t = row.getDouble("t")
            assertEquals(
                "R(t=$t, S=$s)",
                row.getDouble("r"), Fsrs6.retrievability(t, s, p), 1e-12,
            )
        }
    }

    @Test
    fun `retention to interval inversion matches the reference`() {
        val rows = golden.getJSONArray("intervals")
        for (i in 0 until rows.length()) {
            val row = rows.getJSONObject(i)
            val s = row.getDouble("s")
            val req = row.getDouble("req")
            val expected = row.getDouble("days")
            val actual = Fsrs6.intervalDays(s, req, p)
            assertTrue(
                "interval(S=$s, R=$req): expected $expected got $actual",
                abs(expected - actual) <= 1e-9 * maxOf(1.0, abs(expected)),
            )
        }
    }

    /**
     * Every state transition the reference can perform. Split by kind so a failure names which
     * equation drifted rather than just "something is off".
     */
    @Test
    fun `every state transition matches the reference`() {
        val rows = golden.getJSONArray("transitions")
        var difficulty = 0
        var shortTerm = 0
        var longTerm = 0

        for (i in 0 until rows.length()) {
            val row = rows.getJSONObject(i)
            val grade = gradeOf(row.getInt("g"))
            when (row.getString("kind")) {
                "difficulty" -> {
                    val d = row.getDouble("d")
                    assertClose(
                        "nextDifficulty(D=$d, $grade)",
                        row.getDouble("out"), Fsrs6.nextDifficulty(d, grade, p),
                    )
                    difficulty++
                }
                "shortTerm" -> {
                    val s = row.getDouble("s")
                    assertClose(
                        "shortTermStability(S=$s, $grade)",
                        row.getDouble("out"), Fsrs6.shortTermStability(s, grade, p),
                    )
                    shortTerm++
                }
                "longTerm" -> {
                    val s = row.getDouble("s")
                    val d = row.getDouble("d")
                    val r = row.getDouble("r")
                    val actual = if (grade == Grade.Again) {
                        Fsrs6.postLapseStability(MemoryState(s, d), r, p)
                    } else {
                        Fsrs6.recallStability(MemoryState(s, d), r, grade, p)
                    }
                    assertClose("stability(S=$s, D=$d, R=$r, $grade)", row.getDouble("out"), actual)
                    longTerm++
                }
            }
        }

        // Guard against a silently empty or truncated resource passing as "all matched".
        assertTrue("difficulty vectors present", difficulty >= 100)
        assertTrue("short-term vectors present", shortTerm >= 100)
        assertTrue("long-term vectors present", longTerm >= 1000)
    }

    private fun assertClose(what: String, expected: Double, actual: Double) {
        val tol = 1e-9 * maxOf(1.0, abs(expected))
        assertTrue("$what: expected $expected got $actual", abs(expected - actual) <= tol)
    }

    private fun gradeOf(v: Int) = when (v) {
        1 -> Grade.Again
        2 -> Grade.Hard
        3 -> Grade.Good
        else -> Grade.Easy
    }
}
